### ISSUE TITLE
97123 breaks things

### ISSUE THREAD

**Issue by onewheelskyward** [onewheelskyward/lita-onewheel-forecast-io#34]
```
[2016-03-05 19:21:43 UTC] DEBUG: Redis hget failed, performing lookup for 97123
[2016-03-05 19:21:43 UTC] DEBUG: Optimistically geo wrapping 97123!
[2016-03-05 19:21:44 UTC] DEBUG: Geocoder result: '[]'
[2016-03-05 19:21:44 UTC] DEBUG: Geolocation found.  'nil' failed, performing lookup
[2016-03-05 19:21:44 UTC] DEBUG: geocoded: ''
[2016-03-05 19:21:44 UTC] ERROR: Lita::Handlers::OnewheelForecastIo crashed. The exception was:
undefined method `[]' for nil:NilClass
Full backtrace:
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-onewheel-forecast-io-0.1.0/lib/lita/handlers/utils.rb:84:in `geo_lookup'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-onewheel-forecast-io-0.1.0/lib/lita/handlers/irc_handlers.rb:42:in `handle_irc_ansitemp'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in `public_send'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/callback.rb:31:in `call'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in `map'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/handler/chat_router.rb:72:in `dispatch'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:69:in `block in receive'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/2.3.0/set.rb:306:in `each_key'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/2.3.0/set.rb:306:in `each'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in `map'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/lita-4.7.0/lib/lita/robot.rb:66:in `receive'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/lita-irc-34dd1e2e09e5/lib/lita/adapters/irc/cinch_plugin.rb:38:in `dispatch'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/lita-irc-34dd1e2e09e5/lib/lita/adapters/irc/cinch_plugin.rb:18:in `execute'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cinch-2.3.1/lib/cinch/plugin.rb:418:in `call'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cinch-2.3.1/lib/cinch/plugin.rb:418:in `block (2 levels) in __register_matchers'
/home/akreps/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cinch-2.3.1/lib/cinch/handler.rb:99:in `block in call'
```

**Comment by onewheelskyward** [comment]
Thanks, @wagle!
