### ISSUE TITLE
7day dies when day 7 has no temperatureMax

### ISSUE THREAD

**Issue by onewheelskyward** [onewheelskyward/lita-onewheel-forecast-io#41]
```[2017-05-15 19:17:02 UTC] ERROR: Lita::Handlers::OnewheelForecastIo crashed. The exception was:                                                             │························
comparison of NilClass with 75.13 failed                                                                                                                    │························
Full backtrace:                                                                                                                                             │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-onewheel-forecast-io-1.5.3/lib/lita/handlers/forecasts.rb:289:in `each'                  │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-onewheel-forecast-io-1.5.3/lib/lita/handlers/forecasts.rb:289:in `max'                   │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-onewheel-forecast-io-1.5.3/lib/lita/handlers/forecasts.rb:289:in `do_the_seven_day_thing'│························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-onewheel-forecast-io-1.5.3/lib/lita/handlers/irc_handlers.rb:125:in `handle_irc_seven_day│························
'                                                                                                                                                           │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/callback.rb:31:in `public_send'                                           │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/callback.rb:31:in `call'                                                  │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'                          │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:82:in `block in dispatch'                          │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `map'                                        │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `dispatch'                                   │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:69:in `block in receive'                                         │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each_key'                                                                                │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/2.3.0/set.rb:306:in `each'                                                                                    │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `map'                                                      │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `receive'                                                  │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/lita-irc-34dd1e2e09e5/lib/lita/adapters/irc/cinch_plugin.rb:38:in `dispatch'          │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/lita-irc-34dd1e2e09e5/lib/lita/adapters/irc/cinch_plugin.rb:18:in `execute'           │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:418:in `call'                                                 │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cinch-2.3.3/lib/cinch/plugin.rb:418:in `block (2 levels) in __register_matchers'              │························
/home/ec2-user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cinch-2.3.3/lib/cinch/handler.rb:99:in `block in call'
```

**Comment by onewheelskyward** [comment]
Thanks @philtomson for finding this bug!

**Comment by onewheelskyward** [comment]
Test payload

```
{"latitude":45.5248333,"longitude":-122.6779613,"timezone":"America/Los_Angeles","offset":-7,"currently":{"time":1494875844,"summary":"Mostly Cloudy","icon":"partly-cloudy-day","nearestStormDistance":42,"nearestStormBearing":344,"precipIntensity":0,"precipProbability":0,"temperature":57.51,"apparentTemperature":57.51,"dewPoint":44.96,"humidity":0.63,"windSpeed":2.53,"windBearing":213,"visibility":9.98,"cloudCover":0.82,"pressure":1014.13,"ozone":361.55},"minutely":{"summary":"Mostly cloudy for the hour.","icon":"partly-cloudy-day","data":[{"time":1494875820,"precipIntensity":0,"precipProbability":0},{"time":1494875880,"precipIntensity":0,"precipProbability":0},{"time":1494875940,"precipIntensity":0,"precipProbability":0},{"time":1494876000,"precipIntensity":0,"precipProbability":0},{"time":1494876060,"precipIntensity":0,"precipProbability":0},{"time":1494876120,"precipIntensity":0,"precipProbability":0},{"time":1494876180,"precipIntensity":0,"precipProbability":0},{"time":1494876240,"precipIntensity":0,"precipProbability":0},{"time":1494876300,"precipIntensity":0,"precipProbability":0},{"time":1494876360,"precipIntensity":0,"precipProbability":0},{"time":1494876420,"precipIntensity":0,"precipProbability":0},{"time":1494876480,"precipIntensity":0,"precipProbability":0},{"time":1494876540,"precipIntensity":0,"precipProbability":0},{"time":1494876600,"precipIntensity":0,"precipProbability":0},{"time":1494876660,"precipIntensity":0,"precipProbability":0},{"time":1494876720,"precipIntensity":0,"precipProbability":0},{"time":1494876780,"precipIntensity":0,"precipProbability":0},{"time":1494876840,"precipIntensity":0,"precipProbability":0},{"time":1494876900,"precipIntensity":0,"precipProbability":0},{"time":1494876960,"precipIntensity":0,"precipProbability":0},{"time":1494877020,"precipIntensity":0,"precipProbability":0},{"time":1494877080,"precipIntensity":0,"precipProbability":0},{"time":1494877140,"precipIntensity":0,"precipProbability":0},{"time":1494877200,"precipIntensity":0,"precipProbability":0},{"time":1494877260,"precipIntensity":0,"precipProbability":0},{"time":1494877320,"precipIntensity":0,"precipProbability":0},{"time":1494877380,"precipIntensity":0,"precipProbability":0},{"time":1494877440,"precipIntensity":0,"precipProbability":0},{"time":1494877500,"precipIntensity":0,"precipProbability":0},{"time":1494877560,"precipIntensity":0,"precipProbability":0},{"time":1494877620,"precipIntensity":0,"precipProbability":0},{"time":1494877680,"precipIntensity":0,"precipProbability":0},{"time":1494877740,"precipIntensity":0,"precipProbability":0},{"time":1494877800,"precipIntensity":0,"precipProbability":0},{"time":1494877860,"precipIntensity":0,"precipProbability":0},{"time":1494877920,"precipIntensity":0,"precipProbability":0},{"time":1494877980,"precipIntensity":0,"precipProbability":0},{"time":1494878040,"precipIntensity":0,"precipProbability":0},{"time":1494878100,"precipIntensity":0,"precipProbability":0},{"time":1494878160,"precipIntensity":0,"precipProbability":0},{"time":1494878220,"precipIntensity":0,"precipProbability":0},{"time":1494878280,"precipIntensity":0,"precipProbability":0},{"time":1494878340,"precipIntensity":0,"precipProbability":0},{"time":1494878400,"precipIntensity":0,"precipProbability":0},{"time":1494878460,"precipIntensity":0,"precipProbability":0},{"time":1494878520,"precipIntensity":0,"precipProbability":0},{"time":1494878580,"precipIntensity":0,"precipProbability":0},{"time":1494878640,"precipIntensity":0,"precipProbability":0},{"time":1494878700,"precipIntensity":0,"precipProbability":0},{"time":1494878760,"precipIntensity":0,"precipProbability":0},{"time":1494878820,"precipIntensity":0,"precipProbability":0},{"time":1494878880,"precipIntensity":0,"precipProbability":0},{"time":1494878940,"precipIntensity":0,"precipProbability":0},{"time":1494879000,"precipIntensity":0,"precipProbability":0},{"time":1494879060,"precipIntensity":0,"precipProbability":0},{"time":1494879120,"precipIntensity":0,"precipProbability":0},{"time":1494879180,"precipIntensity":0,"precipProbability":0},{"time":1494879240,"precipIntensity":0,"precipProbability":0},{"time":1494879300,"precipIntensity":0,"precipProbability":0},{"time":1494879360,"precipIntensity":0,"precipProbability":0},{"time":1494879420,"precipIntensity":0,"precipProbability":0}]},"hourly":{"summary":"Rain starting this evening.","icon":"rain","data":[{"time":1494874800,"summary":"Mostly Cloudy","icon":"partly-cloudy-day","precipIntensity":0,"precipProbability":0,"temperature":57.51,"apparentTemperature":57.51,"dewPoint":45.48,"humidity":0.64,"windSpeed":2.1,"windBearing":203,"visibility":9.98,"cloudCover":0.81,"pressure":1014.34,"ozone":362.07},{"time":1494878400,"summary":"Mostly Cloudy","icon":"partly-cloudy-day","precipIntensity":0,"precipProbability":0,"temperature":58.32,"apparentTemperature":58.32,"dewPoint":44.41,"humidity":0.6,"windSpeed":3.78,"windBearing":227,"visibility":10,"cloudCover":0.87,"pressure":1013.61,"ozone":360.27},{"time":1494882000,"summary":"Overcast","icon":"cloudy","precipIntensity":0,"precipProbability":0,"temperature":59.66,"apparentTemperature":59.66,"dewPoint":44.49,"humidity":0.57,"windSpeed":5.63,"windBearing":234,"visibility":10,"cloudCover":0.97,"pressure":1012.87,"ozone":358.47},{"time":1494885600,"summary":"Overcast","icon":"cloudy","precipIntensity":0,"precipProbability":0,"temperature":61.02,"apparentTemperature":61.02,"dewPoint":45.36,"humidity":0.56,"windSpeed":6.78,"windBearing":238,"visibility":10,"cloudCover":0.97,"pressure":1012.3,"ozone":358.47},{"time":1494889200,"summary":"Mostly Cloudy","icon":"partly-cloudy-day","precipIntensity":0,"precipProbability":0,"temperature":62.18,"apparentTemperature":62.18,"dewPoint":46.8,"humidity":0.57,"windSpeed":7.87,"windBearing":239,"visibility":10,"cloudCover":0.93,"pressure":1011.6,"ozone":358.47},{"time":1494892800,"summary":"Mostly Cloudy","icon":"partly-cloudy-day","precipIntensity":0.0009,"precipProbability":0.01,"precipType":"rain","temperature":61.7,"apparentTemperature":61.7,"dewPoint":47.16,"humidity":0.59,"windSpeed":8.94,"windBearing":239,"visibility":10,"cloudCover":0.91,"pressure":1010.98,"ozone":358.47},{"time":1494896400,"summary":"Light Rain","icon":"rain","precipIntensity":0.0156,"precipProbability":0.57,"precipType":"rain","temperature":59.51,"apparentTemperature":59.51,"dewPoint":47.46,"humidity":0.64,"windSpeed":8.53,"windBearing":245,"visibility":9.73,"cloudCover":0.93,"pressure":1010.65,"ozone":358.47},{"time":1494900000,"summary":"Light Rain","icon":"rain","precipIntensity":0.0391,"precipProbability":0.69,"precipType":"rain","temperature":56.7,"apparentTemperature":56.7,"dewPoint":47.64,"humidity":0.72,"windSpeed":7.79,"windBearing":251,"visibility":9.36,"cloudCover":0.97,"pressure":1010.45},{"time":1494903600,"summary":"Rain","icon":"rain","precipIntensity":0.0603,"precipProbability":0.75,"precipType":"rain","temperature":54.21,"apparentTemperature":54.21,"dewPoint":47.68,"humidity":0.79,"windSpeed":7.32,"windBearing":247,"visibility":8.33,"cloudCover":1,"pressure":1010.22},{"time":1494907200,"summary":"Rain","icon":"rain","precipIntensity":0.0668,"precipProbability":0.76,"precipType":"rain","temperature":52.52,"apparentTemperature":52.52,"dewPoint":47.1,"humidity":0.82,"windSpeed":7.59,"windBearing":227,"visibility":8.04,"cloudCover":1,"pressure":1009.7},{"time":1494910800,"summary":"Rain","icon":"rain","precipIntensity":0.0693,"precipProbability":0.76,"precipType":"rain","temperature":51.16,"apparentTemperature":51.16,"dewPoint":46.55,"humidity":0.84,"windSpeed":9.94,"windBearing":206,"visibility":7.78,"cloudCover":1,"pressure":1009.04},{"time":1494914400,"summary":"Rain","icon":"rain","precipIntensity":0.0623,"precipProbability":0.75,"precipType":"rain","temperature":50.21,"apparentTemperature":50.21,"dewPoint":46.45,"humidity":0.87,"windSpeed":11.99,"windBearing":199,"visibility":8.02,"cloudCover":1,"pressure":1008.28},{"time":1494918000,"summary":"Rain","icon":"rain","precipIntensity":0.056,"precipProbability":0.74,"precipType":"rain","temperature":49.77,"apparentTemperature":44.96,"dewPoint":46.28,"humidity":0.88,"windSpeed":12.63,"windBearing":201,"visibility":8.18,"cloudCover":1,"pressure":1007.42},{"time":1494921600,"summary":"Light Rain","icon":"rain","precipIntensity":0.0417,"precipProbability":0.7,"precipType":"rain","temperature":49.68,"apparentTemperature":44.91,"dewPoint":46.34,"humidity":0.88,"windSpeed":12.37,"windBearing":209,"visibility":8.99,"cloudCover":1,"pressure":1006.45},{"time":1494925200,"summary":"Light Rain","icon":"rain","precipIntensity":0.035,"precipProbability":0.68,"precipType":"rain","temperature":49.64,"apparentTemperature":45.13,"dewPoint":46.47,"humidity":0.89,"windSpeed":11.47,"windBearing":218,"visibility":9.51,"cloudCover":1,"pressure":1005.54},{"time":1494928800,"summary":"Light Rain","icon":"rain","precipIntensity":0.0321,"precipProbability":0.67,"precipType":"rain","temperature":49.69,"apparentTemperature":45.71,"dewPoint":46.79,"humidity":0.9,"windSpeed":9.85,"windBearing":227,"visibility":9.71,"cloudCover":1,"pressure":1004.66},{"time":1494932400,"summary":"Light Rain","icon":"rain","precipIntensity":0.0342,"precipProbability":0.68,"precipType":"rain","temperature":49.81,"apparentTemperature":46.47,"dewPoint":46.81,"humidity":0.89,"windSpeed":8.17,"windBearing":237,"visibility":9.8,"cloudCover":1,"pressure":1003.85},{"time":1494936000,"summary":"Light Rain","icon":"rain","precipIntensity":0.0373,"precipProbability":0.69,"precipType":"rain","temperature":50.01,"apparentTemperature":50.01,"dewPoint":46.7,"humidity":0.88,"windSpeed":6.64,"windBearing":251,"visibility":9.86,"cloudCover":1,"pressure":1003.35},{"time":1494939600,"summary":"Light Rain","icon":"rain","precipIntensity":0.0421,"precipProbability":0.7,"precipType":"rain","temperature":49.85,"apparentTemperature":47.38,"dewPoint":46.62,"humidity":0.89,"windSpeed":6.21,"windBearing":264,"visibility":9.95,"cloudCover":0.92,"pressure":1003.24},{"time":1494943200,"summary":"Light Rain","icon":"rain","precipIntensity":0.047,"precipProbability":0.72,"precipType":"rain","temperature":49.98,"apparentTemperature":47.2,"dewPoint":46.14,"humidity":0.87,"windSpeed":6.92,"windBearing":292,"visibility":9.97,"cloudCover":0.82,"pressure":1003.42},{"time":1494946800,"summary":"Light Rain","icon":"rain","precipIntensity":0.0475,"precipProbability":0.72,"precipType":"rain","temperature":50.33,"apparentTemperature":50.33,"dewPoint":45.72,"humidity":0.84,"windSpeed":8.6,"windBearing":306,"visibility":9.98,"cloudCover":0.76,"pressure":1003.83},{"time":1494950400,"summary":"Light Rain","icon":"rain","precipIntensity":0.0396,"precipProbability":0.7,"precipType":"rain","temperature":50.89,"apparentTemperature":50.89,"dewPoint":45.34,"humidity":0.81,"windSpeed":9.81,"windBearing":303,"visibility":9.99,"cloudCover":0.78,"pressure":1004.56},{"time":1494954000,"summary":"Light Rain","icon":"rain","precipIntensity":0.0271,"precipProbability":0.65,"precipType":"rain","temperature":51.74,"apparentTemperature":51.74,"dewPoint":44.64,"humidity":0.77,"windSpeed":10.78,"windBearing":296,"visibility":10,"cloudCover":0.84,"pressure":1005.54},{"time":1494957600,"summary":"Light Rain","icon":"rain","precipIntensity":0.018,"precipProbability":0.59,"precipType":"rain","temperature":52.73,"apparentTemperature":52.73,"dewPoint":43.89,"humidity":0.72,"windSpeed":11.61,"windBearing":290,"visibility":10,"cloudCover":0.88,"pressure":1006.52},{"time":1494961200,"summary":"Light Rain","icon":"rain","precipIntensity":0.0157,"precipProbability":0.57,"precipType":"rain","temperature":51.75,"apparentTemperature":51.75,"dewPoint":42.59,"humidity":0.71,"windSpeed":12.45,"windBearing":286,"visibility":10,"cloudCover":0.78,"pressure":1007.4},{"time":1494964800,"summary":"Light Rain","icon":"rain","precipIntensity":0.0168,"precipProbability":0.58,"precipType":"rain","temperature":51.35,"apparentTemperature":51.35,"dewPoint":41.82,"humidity":0.7,"windSpeed":13.12,"windBearing":281,"visibility":10,"cloudCover":0.66,"pressure":1008.25},{"time":1494968400,"summary":"Light Rain","icon":"rain","precipIntensity":0.0195,"precipProbability":0.6,"precipType":"rain","temperature":50.9,"apparentTemperature":50.9,"dewPoint":41.37,"humidity":0.7,"windSpeed":13.47,"windBearing":277,"visibility":10,"cloudCover":0.59,"pressure":1008.97},{"time":1494972000,"summary":"Light Rain","icon":"rain","precipIntensity":0.0249,"precipProbability":0.64,"precipType":"rain","temperature":50.22,"apparentTemperature":50.22,"dewPoint":41.32,"humidity":0.71,"windSpeed":13.38,"windBearing":273,"visibility":10,"cloudCover":0.65,"pressure":1009.46},{"time":1494975600,"summary":"Light Rain","icon":"rain","precipIntensity":0.0319,"precipProbability":0.67,"precipType":"rain","temperature":49.42,"apparentTemperature":44.39,"dewPoint":41.57,"humidity":0.74,"windSpeed":13.06,"windBearing":269,"visibility":10,"cloudCover":0.79,"pressure":1009.82},{"time":1494979200,"summary":"Light Rain","icon":"rain","precipIntensity":0.0357,"precipProbability":0.68,"precipType":"rain","temperature":48.73,"apparentTemperature":43.59,"dewPoint":41.97,"humidity":0.77,"windSpeed":12.79,"windBearing":265,"visibility":10,"cloudCover":0.91,"pressure":1010.27},{"time":1494982800,"summary":"Light Rain","icon":"rain","precipIntensity":0.0332,"precipProbability":0.67,"precipType":"rain","temperature":48.13,"apparentTemperature":42.84,"dewPoint":42.25,"humidity":0.8,"windSpeed":12.76,"windBearing":260,"visibility":9.18,"cloudCover":0.96,"pressure":1010.94},{"time":1494986400,"summary":"Light Rain","icon":"rain","precipIntensity":0.0275,"precipProbability":0.65,"precipType":"rain","temperature":47.58,"apparentTemperature":42.18,"dewPoint":42.56,"humidity":0.83,"windSpeed":12.68,"windBearing":258,"visibility":8.03,"cloudCover":0.97,"pressure":1011.71},{"time":1494990000,"summary":"Light Rain","icon":"rain","precipIntensity":0.022,"precipProbability":0.62,"precipType":"rain","temperature":47.22,"apparentTemperature":41.83,"dewPoint":42.93,"humidity":0.85,"windSpeed":12.31,"windBearing":257,"visibility":7.08,"cloudCover":0.98,"pressure":1012.54},{"time":1494993600,"summary":"Light Rain","icon":"rain","precipIntensity":0.0178,"precipProbability":0.59,"precipType":"rain","temperature":47.15,"apparentTemperature":42.05,"dewPoint":43.39,"humidity":0.87,"windSpeed":11.35,"windBearing":257,"visibility":6.39,"cloudCover":1,"pressure":1013.47},{"time":1494997200,"summary":"Light Rain","icon":"rain","precipIntensity":0.0138,"precipProbability":0.55,"precipType":"rain","temperature":47.19,"apparentTemperature":42.53,"dewPoint":43.82,"humidity":0.88,"windSpeed":10.07,"windBearing":260,"visibility":5.89,"cloudCover":1,"pressure":1014.45},{"time":1495000800,"summary":"Light Rain","icon":"rain","precipIntensity":0.0107,"precipProbability":0.52,"precipType":"rain","temperature":46.98,"apparentTemperature":42.65,"dewPoint":43.99,"humidity":0.89,"windSpeed":9.04,"windBearing":262,"visibility":5.97,"cloudCover":0.99,"pressure":1015.31},{"time":1495004400,"summary":"Drizzle","icon":"rain","precipIntensity":0.009,"precipProbability":0.48,"precipType":"rain","temperature":46.74,"apparentTemperature":42.64,"dewPoint":44.17,"humidity":0.91,"windSpeed":8.37,"windBearing":261,"visibility":7.08,"cloudCover":0.81,"pressure":1015.93},{"time":1495008000,"summary":"Drizzle","icon":"rain","precipIntensity":0.0083,"precipProbability":0.43,"precipType":"rain","temperature":45.89,"apparentTemperature":42.07,"dewPoint":43.72,"humidity":0.92,"windSpeed":7.33,"windBearing":257,"visibility":8.76,"cloudCover":0.57,"pressure":1016.42},{"time":1495011600,"summary":"Drizzle","icon":"rain","precipIntensity":0.0075,"precipProbability":0.37,"precipType":"rain","temperature":45.65,"apparentTemperature":42.36,"dewPoint":43.82,"humidity":0.93,"windSpeed":6.23,"windBearing":251,"visibility":10,"cloudCover":0.44,"pressure":1016.93},{"time":1495015200,"summary":"Drizzle","icon":"rain","precipIntensity":0.0063,"precipProbability":0.29,"precipType":"rain","temperature":46.29,"apparentTemperature":43.22,"dewPoint":44.73,"humidity":0.94,"windSpeed":6.05,"windBearing":249,"visibility":10,"cloudCover":0.5,"pressure":1017.51},{"time":1495018800,"summary":"Drizzle","icon":"rain","precipIntensity":0.0052,"precipProbability":0.22,"precipType":"rain","temperature":46.26,"apparentTemperature":43.06,"dewPoint":44.92,"humidity":0.95,"windSpeed":6.28,"windBearing":248,"visibility":10,"cloudCover":0.65,"pressure":1018.1},{"time":1495022400,"summary":"Mostly Cloudy","icon":"partly-cloudy-night","precipIntensity":0.0043,"precipProbability":0.17,"precipType":"rain","temperature":46.35,"apparentTemperature":43.15,"dewPoint":45.03,"humidity":0.95,"windSpeed":6.31,"windBearing":246,"visibility":10,"cloudCover":0.79,"pressure":1018.7},{"time":1495026000,"summary":"Mostly Cloudy","icon":"partly-cloudy-day","precipIntensity":0.0039,"precipProbability":0.14,"precipType":"rain","temperature":46.83,"apparentTemperature":43.74,"dewPoint":45.24,"humidity":0.94,"windSpeed":6.28,"windBearing":243,"visibility":10,"cloudCover":0.86,"pressure":1019.31},{"time":1495029600,"summary":"Mostly Cloudy","icon":"partly-cloudy-day","precipIntensity":0.0038,"precipProbability":0.14,"precipType":"rain","temperature":47.68,"apparentTemperature":44.72,"dewPoint":45.6,"humidity":0.92,"windSpeed":6.36,"windBearing":241,"visibility":10,"cloudCover":0.91,"pressure":1019.92},{"time":1495033200,"summary":"Overcast","icon":"cloudy","precipIntensity":0.0036,"precipProbability":0.13,"precipType":"rain","temperature":48.72,"apparentTemperature":45.88,"dewPoint":46.05,"humidity":0.9,"windSpeed":6.52,"windBearing":240,"visibility":10,"cloudCover":0.94,"pressure":1020.49},{"time":1495036800,"summary":"Overcast","icon":"cloudy","precipIntensity":0.0031,"precipProbability":0.1,"precipType":"rain","temperature":49.95,"apparentTemperature":47.18,"dewPoint":46.52,"humidity":0.88,"windSpeed":6.88,"windBearing":241,"visibility":10,"cloudCover":0.96,"pressure":1021.04},{"time":1495040400,"summary":"Overcast","icon":"cloudy","precipIntensity":0.0025,"precipProbability":0.07,"precipType":"rain","temperature":51.43,"apparentTemperature":51.43,"dewPoint":47.14,"humidity":0.85,"windSpeed":7.29,"windBearing":243,"visibility":10,"cloudCover":0.96,"pressure":1021.56},{"time":1495044000,"summary":"Overcast","icon":"cloudy","precipIntensity":0.0021,"precipProbability":0.05,"precipType":"rain","temperature":53.07,"apparentTemperature":53.07,"dewPoint":47.99,"humidity":0.83,"windSpeed":7.46,"windBearing":243,"visibility":10,"cloudCover":0.96,"pressure":1021.93},{"time":1495047600,"summary":"Overcast","icon":"cloudy","precipIntensity":0.0021,"precipProbability":0.05,"precipType":"rain","temperature":54.98,"apparentTemperature":54.98,"dewPoint":49.33,"humidity":0.81,"windSpeed":7.06,"windBearing":245,"visibility":10,"cloudCover":0.97,"pressure":1022.14}]},"daily":{"summary":"Light rain today through Wednesday, with temperatures rising to 75°F on Sunday.","icon":"rain","data":[{"time":1494831600,"summary":"Rain starting in the evening.","icon":"rain","sunriseTime":1494852059,"sunsetTime":1494905755,"moonPhase":0.65,"precipIntensity":0.0128,"precipIntensityMax":0.0693,"precipIntensityMaxTime":1494910800,"precipProbability":0.76,"precipType":"rain","temperatureMin":42.99,"temperatureMinTime":1494849600,"temperatureMax":62.18,"temperatureMaxTime":1494889200,"apparentTemperatureMin":42.99,"apparentTemperatureMinTime":1494849600,"apparentTemperatureMax":62.18,"apparentTemperatureMaxTime":1494889200,"dewPoint":44.67,"humidity":0.77,"windSpeed":3.65,"windBearing":232,"visibility":9.57,"cloudCover":0.72,"pressure":1014.07,"ozone":369.39},{"time":1494918000,"summary":"Light rain throughout the day.","icon":"rain","sunriseTime":1494938393,"sunsetTime":1494992225,"moonPhase":0.68,"precipIntensity":0.0303,"precipIntensityMax":0.056,"precipIntensityMaxTime":1494918000,"precipProbability":0.74,"precipType":"rain","temperatureMin":46.98,"temperatureMinTime":1495000800,"temperatureMax":52.73,"temperatureMaxTime":1494957600,"apparentTemperatureMin":41.83,"apparentTemperatureMinTime":1494990000,"apparentTemperatureMax":52.73,"apparentTemperatureMaxTime":1494957600,"dewPoint":44.22,"humidity":0.82,"windSpeed":9.69,"windBearing":263,"visibility":9.12,"cloudCover":0.89,"pressure":1007.96},{"time":1495004400,"summary":"Mostly cloudy throughout the day.","icon":"partly-cloudy-day","sunriseTime":1495024728,"sunsetTime":1495078695,"moonPhase":0.71,"precipIntensity":0.003,"precipIntensityMax":0.009,"precipIntensityMaxTime":1495004400,"precipProbability":0.48,"precipType":"rain","temperatureMin":45.65,"temperatureMinTime":1495011600,"temperatureMax":58.33,"temperatureMaxTime":1495058400,"apparentTemperatureMin":42.07,"apparentTemperatureMinTime":1495008000,"apparentTemperatureMax":58.33,"apparentTemperatureMaxTime":1495058400,"dewPoint":46.95,"humidity":0.85,"windSpeed":5.53,"windBearing":254,"visibility":9.86,"cloudCover":0.71,"pressure":1020.8},{"time":1495090800,"summary":"Mostly cloudy throughout the day.","icon":"partly-cloudy-day","sunriseTime":1495111065,"sunsetTime":1495165164,"moonPhase":0.75,"precipIntensity":0,"precipIntensityMax":0,"precipProbability":0,"temperatureMin":46.66,"temperatureMinTime":1495101600,"temperatureMax":71.43,"temperatureMaxTime":1495148400,"apparentTemperatureMin":46.66,"apparentTemperatureMinTime":1495101600,"apparentTemperatureMax":71.43,"apparentTemperatureMaxTime":1495148400,"dewPoint":49.54,"humidity":0.76,"windSpeed":1.56,"windBearing":258,"visibility":8.99,"cloudCover":0.67,"pressure":1022.3},{"time":1495177200,"summary":"Clear throughout the day.","icon":"clear-day","sunriseTime":1495197404,"sunsetTime":1495251632,"moonPhase":0.78,"precipIntensity":0,"precipIntensityMax":0,"precipProbability":0,"temperatureMin":57.08,"temperatureMinTime":1495206000,"temperatureMax":59.74,"temperatureMaxTime":1495249200,"apparentTemperatureMin":57.08,"apparentTemperatureMinTime":1495206000,"apparentTemperatureMax":59.74,"apparentTemperatureMaxTime":1495249200,"dewPoint":53.5,"humidity":0.84,"windSpeed":2.04,"windBearing":318,"pressure":1022.2},{"time":1495263600,"summary":"Clear throughout the day.","icon":"clear-day","sunriseTime":1495283745,"sunsetTime":1495338099,"moonPhase":0.81,"precipIntensity":0.0007,"precipIntensityMax":0.0016,"precipIntensityMaxTime":1495346400,"precipProbability":0.03,"precipType":"rain","temperatureMin":50.07,"temperatureMinTime":1495281600,"temperatureMax":74.73,"temperatureMaxTime":1495321200,"apparentTemperatureMin":50.07,"apparentTemperatureMinTime":1495281600,"apparentTemperatureMax":74.73,"apparentTemperatureMaxTime":1495321200,"dewPoint":54.31,"humidity":0.75,"windSpeed":2.67,"windBearing":305,"pressure":1020.89},{"time":1495350000,"summary":"Clear throughout the day.","icon":"clear-day","sunriseTime":1495370087,"sunsetTime":1495424565,"moonPhase":0.85,"precipIntensity":0.0021,"precipIntensityMax":0.0027,"precipIntensityMaxTime":1495400400,"precipProbability":0.08,"precipType":"rain","temperatureMin":51.16,"temperatureMinTime":1495368000,"temperatureMax":75.13,"temperatureMaxTime":1495411200,"apparentTemperatureMin":51.16,"apparentTemperatureMinTime":1495368000,"apparentTemperatureMax":75.13,"apparentTemperatureMaxTime":1495411200,"dewPoint":54.14,"humidity":0.77,"windSpeed":2.43,"windBearing":298,"pressure":1020.37},{"time":1495436400,"summary":"Clear throughout the day.","icon":"clear-day","sunriseTime":1495456432,"sunsetTime":1495511030,"moonPhase":0.89,"precipIntensity":0.0005,"precipIntensityMax":0.0022,"precipIntensityMaxTime":1495454400,"precipProbability":0.06,"precipType":"rain","temperatureMin":52.43,"temperatureMinTime":1495468800,"apparentTemperatureMin":52.43,"apparentTemperatureMinTime":1495468800,"dewPoint":49.84,"humidity":0.73,"windSpeed":1.23,"windBearing":307,"pressure":1020.65}]},"flags":{"sources":["lamp","gfs","cmc","nam","rap","rtma","sref","fnmoc","isd","madis","nearest-precip","nwspa","darksky"],"lamp-stations":["KHIO","KMMV","KPDX","KSPB","KTTD","KUAO","KVUO"],"isd-stations":["726836-04201","726836-99999","726881-94273","726881-99999","726959-94281","726959-99999","726980-24229","726985-24242","726985-99999","726986-94261","726986-99999","726987-99999","727918-94298","727918-99999","999999-24229","999999-24274"],"madis-stations":["C7021","D3557","D3762","D7321","D9370","E1617","E1914","E2298","E4831","E6890","E7517","OD103","ODE07","ODE10","ODT10","ODT12"],"units":"us"}}```
